### ISSUE TITLE
Blurry Text

### ISSUE THREAD

**Issue by AbdulQaharRahmani** [stefcameron/text-to-canvas#69]
The quality of text rendered on the canvas does not match the quality of text rendered in the DOM. Despite trying various methods, I have been unable to resolve this issue. The problem is particularly noticeable when users zoom in and out, causing the text to become very blurry. Is there a feature in the canvas-to-text library that can address this, or is this issue unrelated to the library?

**Comment by Esmail-Rahmani** [comment]
I can confirm I am encountering a similar issue. The text quality rendered on the canvas appears lower than that rendered in the DOM across various device resolutions. 
Would be awesome if we could find a fix together!
@stefcameron

**Comment by stefcameron** [comment]
@AbdulQaharRahmani Technically, this library doesn't have "Node/canvas" (e.g. via the `canvas` library) as a support goal. I use it just for a local test.

I would suspect, however, that the quality of the rendering on Node/canvas is more due to the `canvas` library than this one. `text-to-canvas` is strictly using standard HTML `<canvas>` APIs. Whatever other library you use to render to (by creating a 2D context and giving that to `text-to-canvas`), so long as it supports that API, it'll render.

@Esmail-Rahmani Top of mind possible issue is anti-aliasing, _maybe_. HTML `<canvas>` is anti-aliased [by default](https://stackoverflow.com/questions/195262/can-i-turn-off-antialiasing-on-an-html-canvas-element) and this can be _disabled_, but that would be the _opposite_ of what you're wanting as output (i.e. a smoother output instead of a crisper one, assuming this is the issue).

So perhaps Node/canvas is __not__ anti-aliased by default and this needs to be enabled (i.e. opt-in instead of opt-out like in HTML), or maybe it doesn't support anti-aliasing at all?

**Comment by AbdulQaharRahmani** [comment]
@stefcameron the blurry text problem that i faced was not related to this library rather it was related to density pixels. here is how one can solve it.
```
function createHiPPICanvas(width, height) {
    const ratio = window.devicePixelRatio;
    const canvas = document.createElement("canvas");

    canvas.width = width * ratio;
    canvas.height = height * ratio;
    canvas.style.width = width + "px";
    canvas.style.height = height + "px";
    canvas.getContext("2d").scale(ratio, ratio);

    return canvas;
}
```
or you can manually set the ratio 2 or 3.

**Comment by stefcameron** [comment]
@AbdulQaharRahmani Thank you for updating us with your solution! I [added](https://github.com/stefcameron/text-to-canvas/commit/f3d01ac8b7146fc8233299b0e43f00a24092b466) a new help topic for this in the README.
