### ISSUE TITLE
VERY outdated dependencies

### ISSUE THREAD

**Issue by ivanjaros** [stefcameron/text-to-canvas#73]
I just installed the plugin and I got:
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehens
ive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
```

**Comment by stefcameron** [comment]
Hi @ivanjaros,

I'm not sure where those are coming from. Here is the output from a fresh install of this repository's dependencies:

```bash
/text-to-canvas$ npm install

> text-to-canvas@1.1.2 prepare
> npm run build


> text-to-canvas@1.1.2 build
> rm -rf ./dist && npm run build:browser && npm run build:node && npm run build:types


> text-to-canvas@1.1.2 build:browser
> vite build --config build/vite.config.esm.mts && vite build --config build/vite.config.cjs.mts

vite v5.2.12 building for production...
✓ 8 modules transformed.
../dist/text-to-canvas.esm.min.js  9.74 kB │ gzip: 3.48 kB │ map: 45.07 kB
✓ built in 240ms
vite v5.2.12 building for production...
✓ 8 modules transformed.
../dist/text-to-canvas.min.js  6.60 kB │ gzip: 2.78 kB │ map: 44.00 kB
../dist/text-to-canvas.umd.min.js  6.77 kB │ gzip: 2.89 kB │ map: 43.97 kB
✓ built in 312ms

> text-to-canvas@1.1.2 build:node
> vite build --config build/vite.config.node.mts

vite v5.2.12 building for production...
✓ 8 modules transformed.
../dist/text-to-canvas.mjs  15.21 kB │ gzip: 4.08 kB
../dist/text-to-canvas.cjs  15.49 kB │ gzip: 4.15 kB
✓ built in 226ms

> text-to-canvas@1.1.2 build:types
> tsc src/lib/index.ts --declaration --emitDeclarationOnly --outDir dist/types


added 230 packages, and audited 231 packages in 28s

58 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

And since a moderate severity vulnerability was reported:

```bash
/text-to-canvas$ npm audit
# npm audit report

tar  <6.2.1
Severity: moderate
Denial of service while parsing a tar file due to lack of folders count validation - https://github.com/advisories/GHSA-f5x3-32g6-xq36
fix available via `npm audit fix`
node_modules/tar

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix
```

So I fixed it in https://github.com/stefcameron/text-to-canvas/commit/c0d3e959879fc389c3ef7dbb11831cf9f442bb0a:

```bash
/text-to-canvas$ npm audit fix

up to date, audited 231 packages in 5s

58 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I can see the dependencies you pointed out in the lock file (package-lock.json) though I'm not sure how you're getting those warnings.

Maybe you could try deleting the lock file and installing everything anew and let me know if you still see those same warnings.

Also keep in mind that this library doesn't depend on __anything__ at runtime. So wherever those outdated packages are coming from (I suspect, though cannot confirm, it's from the entirely __optional__ `canvas` dependency, which is purely for demo purposes since the library doesn't formally support Canvas anyway), none of that code will get used at runtime (at least not by `text-to-canvas`).

**Comment by ivanjaros** [comment]
> I'm not sure where those are coming from

When i looked at it, i think it was that rimraf that had old dependencies. But have since removed the library so don't know much more. I just installed it like any other library so I found it strange.

**Comment by stefcameron** [comment]
Well, every dependency listed in package.json is at its latest version, and those aren't old things, at least not on the surface. But they may very well be using old things under the hood.

`rimraf`, per the lock file, appears to coming from `node-pre-gyp`, which is related to `canvas`, which is optional, and also `eslint`, and that's modern. It's still on v8 because a lot of the ecosystem around ESLint hasn't upgraded to v9 yet.

So the dependencies are as good as they are going to get. I'm going to close this issue now.
